GET http://localhost:5285/dinners  HTTP/1.1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZGRiZGViYy0yNGNkLTRmNmUtOTNlYi00YTkxNWQ0NzA1YmUiLCJqdGkiOiI5MzJmMGZlMS1hMjQwLTQ0NWYtYWEyZi1mNTNmMzdhNDk0NjciLCJnaXZlbl9uYW1lIjoiUmFqZXNoIiwiZmFtaWx5X25hbWUiOiJKYWtrYSIsImV4cCI6MTY5ODc2NjM2OCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.r6t_D78tXvIEClMyH9510dwig-EWMTxiAIcuZMoLyNM


